# Generated by Django 3.0.4 on 2020-03-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('price', models.FloatField(null=True)),
                ('c_date', models.DateField(null=True)),
            ],
        ),
    ]
