# Generated by Django 3.0.4 on 2020-03-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200305_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='c_date',
            field=models.DateTimeField(null=True),
        ),
    ]
