# Generated by Django 3.0.4 on 2020-03-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200306_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='c_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
